Fix init script and supervisor conf

diff --git a/misc/kasa b/misc/kasa
--- a/misc/kasa
+++ b/misc/kasa
@@ -1,6 +1,4 @@
-#!/bin/sh
-# Start running the Kasa server
-#
+#! /bin/sh
 ### BEGIN INIT INFO
 # Provides: kasa
 # Required-Start: $network $remote_fs $syslog $time
@@ -13,56 +11,155 @@
 # Description: Starts Kasa IPython notebook server
 ### END INIT INFO 
 
+# Author: Berk Birand <berk@berkbirand.com>
+# Version 0.0
+# Based on supervisor script by Leonard Norrgard
+#  <https://raw.githubusercontent.com/Supervisor/initscripts/master/debian-norrgard>
+
+# Do NOT "set -e"
+PROJECT_ROOT="/home/pi/kasa"
+SUPERVISOR_CONFIG="$PROJECT_ROOT/supervisor.conf"
+
+PATH=/usr/local/bin:/sbin:/usr/sbin:/bin:/usr/bin
+DESC="Kasa system"
 NAME=kasa
+DAEMON=$PROJECT_ROOT/ve/bin/supervisord 
+SUPERVISORCTL="$PROJECT_ROOT/ve/bin/supervisorctl -c ${SUPERVISOR_CONFIG}"
 PIDFILE=/var/run/$NAME.pid
+DAEMON_ARGS="-c ${SUPERVISOR_CONFIG} --pidfile ${PIDFILE}"
+SCRIPTNAME=/etc/init.d/$NAME
+
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
+
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
+. /lib/lsb/init-functions
+
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+        [ -e $PIDFILE ] && return 1
+
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+		$DAEMON_ARGS \
+		|| return 2
+	# Add code here, if necessary, that waits for the process to be ready
+	# to handle requests from services started subsequently which depend
+	# on this one.  As a last resort, sleep for some time.
+}
+
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+    [ -e $PIDFILE ] || return 1
+
+	# Stop all processes under supervisord control and shut down
+	#$SUPERVISORCTL stop all
+	$SUPERVISORCTL shutdown
+
+	rm -f $PIDFILE
+
+	#start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+	#RETVAL="$?"
+	#[ "$RETVAL" = 2 ] && return 2
+	# Wait for children to finish too if this is a daemon that forks
+	# and if the daemon is only ever run from this initscript.
+	# If the above conditions are not satisfied then add some other code
+	# that waits for the process to drop all resources that could be
+	# needed by services started subsequently.  A last resort is to
+	# sleep for some time.
+	#start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+	#[ "$?" = 2 ] && return 2
+	# Many daemons don't delete their pidfiles when they exit.
+	#return "$RETVAL"
+}
+
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+	#
+	# If the daemon can reload its configuration without
+	# restarting (for example, when it is sent a SIGHUP),
+	# then implement that here.
+	#
+	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+	return 0
+}
 
 case "$1" in
-start)
-    echo "Starting kasa"
-    # Make sure that the BT chip is up (if present?)
-    hciconfig hci0 up
-
-    # Start the IPython notebook
-    #PID=$(/home/pi/kasa/ve/bin/ipython notebook --profile-dir=/home/pi/kasa/profile 2>&1 >> /dev/null & echo $!)
-    /home/pi/kasa/ve/bin/ipython notebook --profile-dir=/home/pi/kasa/profile 2>&1 >> /dev/null &
-    PID=$!
-    #echo "PID is $PID"
-
-    if [ -z $PID ]; then
-	    printf "%s\n" "Fail"
-    else
-	    echo $PID > $PIDFILE
-	    printf "%s\n" "Ok"
-    fi
-
-;;
-
-stop)
-    echo "Stopping kasa"
-    hciconfig hci0 down
-
-    PID=$(cat $PIDFILE)
-    if [ -f $PIDFILE ]; then
-	    kill -HUP $PID
-	    printf "%s\n" "Ok"
-	    rm -f $PIDFILE
-    else
-	    printf "%s\n" "pidfile not found"
-    fi
-;;
-
-restart)
-  	$0 stop
-	$0 start
-;;
-
-*)
-    echo "Usage: /etc/init.d/kasa {start|stop|restart}"
-    exit 1
-;;
-
+  start)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	do_start
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
+  stop)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
+  #reload|force-reload)
+	#
+	# If do_reload() is not implemented then leave this commented out
+	# and leave 'force-reload' as an alias for 'restart'.
+	#
+	#log_daemon_msg "Reloading $DESC" "$NAME"
+	#do_reload
+	#log_end_msg $?
+	#;;
+  restart|force-reload)
+	#
+	# If the "reload" option is implemented then remove the
+	# 'force-reload' alias
+	#
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	  *)
+	  	# Failed to stop
+		log_end_msg 1
+		;;
+	esac
+	;;
+  *)
+	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
+	exit 3
+	;;
 esac
 
-exit 0
-
-
+:
